# Azure DevOps Pipeline configuration for master branch.
trigger:
  - master

variables:
  COMMON_CMAKE_ARGS: >-
    -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra
    -DPACKAGE_VENDOR=XYB
    -DPACKAGE_VERSION=$(Build.SourceVersion)

jobs:
- job: Build_Windows_X86_Release
  variables:
    WORKING_DIR: 'build.x86'
  timeoutInMinutes: 180
  pool:
    vmImage: vs2017-win2016
  steps:
    - checkout: self
    - task: CMake@1
      inputs:
        workingDirectory: '$(WORKING_DIR)'
        cmakeArgs: '$(COMMON_CMAKE_ARGS) -G "Visual Studio 15 2017" -A Win32 -Thost=x64 ..\\llvm'
    - task: VSBuild@1
      inputs:
        solution: '$(WORKING_DIR)\\tools\\clang\\tools\\extra\\clang-tidy\\tool\\clang-tidy.vcxproj'
        vsVersion: 15.0
        platform: Win32
        configuration: Release
        maximumCpuCount: true
        msbuildArchitecture: x64
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(WORKING_DIR)\\Release\\bin\\clang-tidy.exe'
        includeRootFolder: false
        archiveType: '7z'
        archiveFile: '$(WORKING_DIR)\\Release\\bin\\clang-tidy.x86.7z'
        replaceExistingArchive: true
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(WORKING_DIR)\\Release\\bin\\clang-tidy.x86.7z'
        artifactName: 'clang-tidy.x86'
- job: Build_Windows_X64_Release
  variables:
    WORKING_DIR: 'build.x64'
  timeoutInMinutes: 180
  pool:
    vmImage: vs2017-win2016
  steps:
    - checkout: self
    - task: CMake@1
      inputs:
        workingDirectory: $(WORKING_DIR)
        cmakeArgs: '$(COMMON_CMAKE_ARGS) -G "Visual Studio 15 2017" -A x64 -Thost=x64 ..\\llvm'
    - task: VSBuild@1
      inputs:
        solution: '$(WORKING_DIR)\\tools\\clang\\tools\\extra\\clang-tidy\\tool\\clang-tidy.vcxproj'
        vsVersion: 15.0
        platform: x64
        configuration: Release
        maximumCpuCount: true
        msbuildArchitecture: x64
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(WORKING_DIR)\\Release\\bin\\clang-tidy.exe'
        includeRootFolder: false
        archiveType: '7z'
        archiveFile: '$(WORKING_DIR)\\Release\\bin\\clang-tidy.x64.7z'
        replaceExistingArchive: true
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(WORKING_DIR)\\Release\\bin\\clang-tidy.x64.7z'
        artifactName: 'clang-tidy.x64'
- job: Publish
  dependsOn:
    - Build_Windows_X86_Release
    - Build_Windows_X64_Release
  steps:
    - checkout: self
      persistCredentials: true
    - task: DownloadPipelineArtifact@2
      inputs:
        targetPath: build
    - task: GitHubRelease@0
      displayName: 'Delete old release'
      inputs:
        gitHubConnection: xyb
        repositoryName: 'xieyubo/llvm-project'
        action: delete
        tag: 'latest'
      continueOnError: true
    - task: CmdLine@2
      displayName: 'Delete old tag'
      inputs:
        script: 'git push origin :refs/tags/latest'
    - task: GitHubRelease@0
      displayName: 'Create new release'
      inputs:
        gitHubConnection: xyb
        repositoryName: 'xieyubo/llvm-project'
        action: create
        target: '$(Build.SourceVersion)'
        tagSource: manual
        tag: 'latest'
        assets: |
          build/clang-tidy.x86/clang-tidy.x86.7z
          build/clang-tidy.x64/clang-tidy.x64.7z
        assetUploadMode: delete
        isPreRelease: true
        addChangeLog: false
